name: Unit Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
   
    - uses: actions/checkout@v2
    
      
    - name: make all
      run:  make -C source/
    - name: Change mode
      run: chmod a+x ./all.out
    - name: unit test
      run: cd source && ./all.out
